// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTPLfheMOy_f-HArh4GJ-i6ImWgNJPY5k',
    appId: '1:638851261502:web:2c16ba6c56fb9e50211d6f',
    messagingSenderId: '638851261502',
    projectId: 'inventory-f29cd',
    authDomain: 'inventory-f29cd.firebaseapp.com',
    storageBucket: 'inventory-f29cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0j2mmaDjGlcTi6jrHRH95XfFT_2Uru_E',
    appId: '1:638851261502:android:43b8ab9f2482a503211d6f',
    messagingSenderId: '638851261502',
    projectId: 'inventory-f29cd',
    storageBucket: 'inventory-f29cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn1lS8Bl9keUCnyDdTWjDphzJdxRCNM2I',
    appId: '1:638851261502:ios:b40932c4e5f5c968211d6f',
    messagingSenderId: '638851261502',
    projectId: 'inventory-f29cd',
    storageBucket: 'inventory-f29cd.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn1lS8Bl9keUCnyDdTWjDphzJdxRCNM2I',
    appId: '1:638851261502:ios:b40932c4e5f5c968211d6f',
    messagingSenderId: '638851261502',
    projectId: 'inventory-f29cd',
    storageBucket: 'inventory-f29cd.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTPLfheMOy_f-HArh4GJ-i6ImWgNJPY5k',
    appId: '1:638851261502:web:807afdf937ea5649211d6f',
    messagingSenderId: '638851261502',
    projectId: 'inventory-f29cd',
    authDomain: 'inventory-f29cd.firebaseapp.com',
    storageBucket: 'inventory-f29cd.firebasestorage.app',
  );
}
